script_task:
  description: >
    Escreva um roteiro vertical (≤40 palavras) sobre {topic},
    incluindo hook, dado curioso e CTA. O ano atual é {current_year}
  expected_output: >
    Markdown com cabeçalho "ROTEIRO" e o texto em uma linha.
  agent: script_writer

thumbnail_task:
  depends_on: >
    [task1]
  description: >
    Crie uma imagem 1024×1024 minimalista que sintetize o roteiro.
  expected_output: >
    URL pública da imagem PNG.
  agent: thumbnail_designer

# narrative_task:
#   depends_on: >
#     [task1]
#   description: >
#     create a 15 seconds narration based on the following script: {script}
#   expected_output: >
#     An audio file with the voice over.
#   agent: video_narrator